

{0}------------------------------------------------

## **Topic 6 Ethernet Switching Study Guide**

| 1.                  | List two                                                                                                                                                                                                                                                                                                                                                                        | characteristics of Ethernet                                                                               | Encapsulation.         | (S3)                                                                                                                                                                                                                                                                         |      | (4) |  |
|---------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|-----|--|
|                     | •<br>•                                                                                                                                                                                                                                                                                                                                                                          | Operates in the data link layer and the physical layer.<br>Defined in the IEEE 802.2 and 802.3 standards. |                        |                                                                                                                                                                                                                                                                              |      |     |  |
| 2.                  |                                                                                                                                                                                                                                                                                                                                                                                 | Describe briefly the two sublayers of the Data Link layer?                                                |                        | (S4)                                                                                                                                                                                                                                                                         |      | (8) |  |
|                     | •<br>LLC Sublayer:<br>•<br>Communicates between the networking software at the upper layers and the device hardware<br>at the lower layers.<br>•<br>Places information in the frame to identify which network layer protocol is used for the frame.<br>•<br>MAC Sublayer:<br>•<br>Implemented in hardware.<br>•<br>Responsible for data encapsulation and media access control. |                                                                                                           |                        |                                                                                                                                                                                                                                                                              |      |     |  |
| 3.                  |                                                                                                                                                                                                                                                                                                                                                                                 | What is the size of an Ethernet frame?                                                                    | (S7)                   |                                                                                                                                                                                                                                                                              |      | (2) |  |
|                     | •                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                           |                        | The minimum Ethernet frame size is 64 bytes and the maximum are 1518 bytes.                                                                                                                                                                                                  |      |     |  |
| 4.                  | What is<br>Runt and Jumbo frames and how do switches handle them?                                                                                                                                                                                                                                                                                                               |                                                                                                           |                        |                                                                                                                                                                                                                                                                              | (S7) | (6) |  |
|                     | •<br>•<br>Frames<br>•<br>drops the frame.                                                                                                                                                                                                                                                                                                                                       |                                                                                                           |                        | Any frame that is less than 64 bytes is considered a "collision fragment" or "runt frame".<br>that has more than 1500 bytes are considered "jumbo" or "baby giant frames".<br>If the size of a transmitted frame less than minimum or over the maximum, the receiving device |      |     |  |
| 5.                  | Identify                                                                                                                                                                                                                                                                                                                                                                        | the Ethernet frame fields below.                                                                          | (S7)                   |                                                                                                                                                                                                                                                                              |      | (4) |  |
|                     | PREAMBLE                                                                                                                                                                                                                                                                                                                                                                        | Destination<br>MAC Address.                                                                               | Source MAC<br>Address. | Type / Length.                                                                                                                                                                                                                                                               | DATA | FCS |  |
| 6.                  | Convert<br>•<br>3D to decimal: 61<br>•                                                                                                                                                                                                                                                                                                                                          | the following:<br>(S8, S9)<br>E4                                                                          |                        |                                                                                                                                                                                                                                                                              |      | (4) |  |
| 228 to Hexadecimal: |                                                                                                                                                                                                                                                                                                                                                                                 |                                                                                                           |                        |                                                                                                                                                                                                                                                                              |      |     |  |

{1}------------------------------------------------

- 7. What are the two parts of the MAC address? **(S11) (2)**
  - **1. organizationally unique identifier (OUI).**
  - **2. Vendor assigned values.**
- 8. Explain how a NIC does frame processing. **(S12) (6)**
  - **When a NIC receives an Ethernet frame, it examines the destination MAC address to see if it matches the physical MAC address that is stored in RAM.**
  - **If there is no match, the device discards the frame.**
  - **If there is a match, it passes the frame up the OSI layers, where the de-encapsulation process takes place.**
- 9. Describe the role of each type of MAC address and give an example of each: **(S13-S15) (8)**
  - 1. Unicast MAC:
- **A unicast MAC address is used when a frame is sent from a single transmitting device to a single destination device.**
  - 2. Broadcast MAC:
- **broadcast frame is received and processed by every device on the LAN, has a destination MAC address of FF-FF-FF-FF-FF-FF, is flooded out all Ethernet switch ports except the incoming port, and is not forwarded by a router.**
  - 3. Multicast MAC:
  - **Recognized by the hexadecimal numbers 01-00-5E at the beginning of the address in the case of IPv4 multicast packet, required by the multicast IP address, and received and processed by a group of devices that belong to the same multicast group.**

{2}------------------------------------------------

- 10. Explain how an Ethernet switch forwards frames. **(S16) (4)**
  - **Uses Layer 2 MAC addresses to make forwarding decisions.**
  - **Examines its MAC address table to make a forwarding decision for each frame.**
- 11. Explain the learning, forwarding and filtering of the frame switching process. **(S17-S20) (6)**
  - 1. **Learning**
    - **The switch examines the source MAC Address of every frame that enters the switch and the incoming port number.**
    - **If the source MAC address does not exist in the MAC table, it is added to the table along with the incoming port number.**
    - **If the source MAC address does exist in the MAC table, the switch updates the refresh timer for that entry. By default, most Ethernet switches keep an entry in the table for 5 minutes.**
  - 2. **Forwarding**
    - **If the destination MAC address is a unicast address, the switch will look for a match between the destination MAC address of the frame and an entry in its MAC address table.**
    - **If the destination MAC address is not in the table, the switch will forward the frame to all ports except the incoming port.**
    - **If the destination MAC address is a broadcast or a multicast, the frame is also forwarded to all ports except the incoming port.**
    - **Filtering**
    - **If the destination MAC address is in the table, the switch will forward the frame to the specified port.**
    - **3. Filtering:**
      - **If the destination MAC address is in the table, the switch will forward the frame to the specified port.**
- 12. Explain auto-MDIX and how it is used: **(S24) (2)**
  - **(auto-MDIX) feature to enable the device to automatically detect the type of cable attached to the port and configures the interfaces accordingly.**
- 13. List the purpose of two primary addresses assigned to a device on an Ethernet LAN. **(S25) (2)**
  - **Layer 2 physical address (MAC address)**: Used for NIC to NIC communications on the same Ethernet network.
  - **Layer 3 logical address (IP address)**: Used to send the packet from the source device to the destination device.

{3}------------------------------------------------

| 14. | What is the destination MAC address when the final destination IP address is on the same network?<br>(S25)                                                                                                                                                                                                                                                                                                                           |     |  |  |  |  |
|-----|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----|--|--|--|--|
|     | •<br>If a destination IP address is on the<br>same network, the destination MAC address will be that of the<br>destination device                                                                                                                                                                                                                                                                                                    |     |  |  |  |  |
| 15. | What is the destination MAC address when the final destination is on a remote network? (S26)                                                                                                                                                                                                                                                                                                                                         | (2) |  |  |  |  |
|     | •<br>When the destination IP address is on a remote network, the destination MAC address is that of the<br>default gateway.                                                                                                                                                                                                                                                                                                          |     |  |  |  |  |
| 16. | What are the two basic functions of ARP?<br>(S27)                                                                                                                                                                                                                                                                                                                                                                                    | (4) |  |  |  |  |
|     | 1.<br>Resolving IPv4 addresses to MAC addresses                                                                                                                                                                                                                                                                                                                                                                                      |     |  |  |  |  |
|     | 2.<br>Maintaining an ARP table of IPv4 to MAC address mappings.                                                                                                                                                                                                                                                                                                                                                                      |     |  |  |  |  |
| 17. | Explain<br>the steps involved in ARP process.<br>(S28)                                                                                                                                                                                                                                                                                                                                                                               | (8) |  |  |  |  |
|     | 1.<br>Host A searches its ARP table for the MAC address of host D. Initially, the ARP table is empty.<br>2.<br>Host A broadcasts an ARP request (broadcast MAC (FF)) to learn the MAC address of the<br>host D.<br>3.<br>Host D sends an ARP reply that includes its MAC address, while hosts B and C ignore the ARP<br>request.<br>4.<br>Host A receives the ARP reply, takes the information from it and adds it to its ARP table. |     |  |  |  |  |
| 18. | What are the two ways a device can learn a MAC address?<br>(S17, S27)                                                                                                                                                                                                                                                                                                                                                                | (4) |  |  |  |  |
|     | 1.<br>ARP table.<br>2.<br>Through learning process.                                                                                                                                                                                                                                                                                                                                                                                  |     |  |  |  |  |
| 19. | How are entries removed from an ARP table?<br>(S30)                                                                                                                                                                                                                                                                                                                                                                                  | (4) |  |  |  |  |
|     | •<br>When an ARP cache timer expires.                                                                                                                                                                                                                                                                                                                                                                                                |     |  |  |  |  |
|     | •<br>Manually by the administrator.                                                                                                                                                                                                                                                                                                                                                                                                  |     |  |  |  |  |
| 20. | Explain the two<br>main ARP issues.<br>(S32)                                                                                                                                                                                                                                                                                                                                                                                         | (4) |  |  |  |  |
|     | •<br>Excessive ARP broadcasts can cause some reduction in performance.                                                                                                                                                                                                                                                                                                                                                               |     |  |  |  |  |
|     | •<br>ARP replies can be spoofed by a threat actor to perform an ARP poisoning attack.                                                                                                                                                                                                                                                                                                                                                |     |  |  |  |  |